# Generated by Django 3.1.2 on 2020-12-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'db_table': 'alquiler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ControlHorario',
            fields=[
                ('id_control_horario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('ingreso', models.TimeField()),
                ('salida', models.TimeField()),
            ],
            options={
                'db_table': 'control_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id_descuento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('monto', models.FloatField()),
            ],
            options={
                'db_table': 'descuento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=30)),
                ('razon_social', models.CharField(max_length=40)),
                ('direccion', models.TextField()),
                ('contacto', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'espacio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_control', models.CharField(max_length=30)),
                ('autorizacion', models.IntegerField()),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id_incidentes', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'incidentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPagos',
            fields=[
                ('id_plan_de_pagos', models.AutoField(primary_key=True, serialize=False)),
                ('monto_cuota', models.FloatField()),
                ('num_cuotas', models.IntegerField()),
                ('cuotas_pagadas', models.IntegerField()),
            ],
            options={
                'db_table': 'plan_pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroCaja',
            fields=[
                ('id_registro_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('monto', models.FloatField()),
                ('tipo', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'registro_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroParqueo',
            fields=[
                ('id_parqueo', models.AutoField(primary_key=True, serialize=False)),
                ('entrada', models.DateTimeField()),
                ('salida', models.DateTimeField()),
            ],
            options={
                'db_table': 'registro_parqueo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifas', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'tarifa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TarifaAlquiler',
            fields=[
                ('id_tarifa_alquiler', models.AutoField(primary_key=True, serialize=False)),
                ('meses', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'tarifa_alquiler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEspacio',
            fields=[
                ('id_tipo_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_espacio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id_tipo_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=45)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
    ]
